### ISSUE TITLE
Support for $ref?

### ISSUE THREAD

**Issue by chinshr** [json-schema-form/json-schema-form-core#1]
Do you have an ETA for $ref support as in the example below?

``` javascript
{
  "$schema": "http://json-schema.org/draft-04/schema#",

  "definitions": {
    "notes": {
      "type": "object",
      "properties": {
        "classification": {
          "type": "string",
          "enum": [
            "Lite",
            "Premium",
            "Plus",
          ]
        }
      }
    }
  },

  "title": "Customer Creative Brief",
  "type": "object",
  "properties": {
    "notes": { "$ref": "#/definitions/notes" }
  }
}
```

**Comment by nicklasb** [comment]
The situation is that the core it being broken out and that the community is preparing a 1.0 release. 
As this is a FOSS-project, ETA:s are difficult, so I would not dare any precises guesses and probably others won't either.
It would be nice to get local $ref in 1.0, but it may also be in 1.1, the consensus seem to be that anyOf has slightly higher priority (as this can be worked around by server side resolution in many cases). 

But I suppose we are talking a couple of months at the most, hopefully sooner.
The discussion has been here, with an apparent work around in the original discussion about you could use until the formal support is added.

https://github.com/json-schema-form/angular-schema-form/issues/69

**Comment by Anthropic** [comment]
@chinshr $ref is supported in the latest versions
